sudo: required  # for 3.7, see https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install: pip install tox-travis
script: tox
